[project]
name = "domainbed"
version = "0.1.0"
requires-python = ">=3.11,<3.12"

dependencies = [
    "torch==2.5.*",
    "torchvision==0.20.*",
    "torchaudio==2.5.*",
    "transformers>=4.46,<5",
    "timm",
    "soundfile",
    "tensorboard",
    "wilds",
    "numpy",
    "pillow",
    "matplotlib>=3.11.1",
    "spectrum>=0.10.0",
    "psutil>=7.2.2",
]
